### ISSUE TITLE
document is not defined

### ISSUE THREAD

**Issue by xieshiyi** [TechStark/opencv-js#25]
when I use it in node.js，run `cv.imread()` ，it prompts that the document is not defined。

**Comment by MezianeKhalil** [comment]
how you fix this issue??

**Comment by Noitidart** [comment]
i get this same issue, how did you fix?

**Comment by barratt** [comment]
Apologies for necro, if anyone encounters this in future I do not believe some functions are available using Node as it references 'document' (used on the web)

I found this example https://github.com/TechStark/opencv-js-examples/blob/main/opencv-js-node-example/src/esm/index.mjs which gives an alternative way of loading the images in instead of imread, with this I'm able to perform template matching and get locations. 

I've also found that: imwrite and imshow also does not work which I haven't yet found a work around for, since messing with this I've been referred to the library opencv4nodejs-prebuilt-install which is a apparently more usable on Node
